#!/bin/bash
folder_name="longhaul-covid"
remote_server_user="root"
remote_server_ip='64.225.118.194'
local_db_user="root"
local_db_pwd="root"
local_db_port="3306"
db_name="longhaul-covid-laravel"
db_port="3306"
db_user="root"
db_pwd="vbGZEEPZXcyGRQky6"
branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
db_location="/var/www/$folder_name--$branch/_db"
project_folder="/var/www/$folder_name--$branch"

# chmod -R 600 keys/*
#

case ${@:1:1} in
    init)
        #CREATE SCRIPT TO CREAT THE DB BASED ON BRANCH!!!!!!!!!!!
    ;;
    deploy)
        ssh $remote_server_user@$remote_server_ip -o StrictHostKeyChecking=no "test -d $project_folder || mkdir $project_folder"
        rsync -avz ./ $remote_server_user@$remote_server_ip:$project_folder
        ssh $remote_server_user@$remote_server_ip -o StrictHostKeyChecking=no "sudo chmod 777 -R $project_folder/storage"
		ssh $remote_server_user@$remote_server_ip -o StrictHostKeyChecking=no "sudo mv $project_folder/.env.production $project_folder/.env"
    ;;
    sync)
        j=$(printf "%s" 'Host ' $HOSTNAME)
        NOW=$(date +"%m-%d-%Y-%r")
        a=$(printf "%s" 'Time ' $NOW)
        TS=$(date +"%s")
        v=$(printf "%s" 'DB ' $TS'.sql')
        printf '%s %s\n%s %s\n%s %s\n\n' $j $a $v>> _db/log.txt
        mysqldump -h 127.0.0.1 -u$local_db_user --password=$local_db_pwd -P $local_db_port --force $db_name > _db/${TS}.sql
        kill -9 $(lsof -t -i:3307) 2> /dev/null
        echo $db_pwd|pbcopy
        ssh -f -L 3307:127.0.0.1:3306 -t -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no $remote_server_user@$remote_server_ip -N
        mysql -e "drop database $db_name;" -P $local_db_port -h 127.0.0.1 -u$local_db_user --password=$local_db_pwd
        mysql -e "create database $db_name CHARACTER SET utf8 COLLATE utf8_general_ci;" -P $local_db_port -h 127.0.0.1 -u$local_db_user --password=$local_db_pwd
        mysqldump -h 127.0.0.1 -P $db_port -u$db_user -p$db_pwd $db_name > /tmp/$db_name.sql
        mysql -h 127.0.0.1 -u$local_db_user --password=$local_db_pwd -P $local_db_port --force $db_name < /tmp/$db_name.sql
        rm /tmp/$db_name.sql
        kill -9 $(lsof -t -i:3307) 2> /dev/null
    ;;
    export-db)
        j=$(printf "%s" 'Host ' $HOSTNAME)
        NOW=$(date +"%m-%d-%Y-%r")
        a=$(printf "%s" 'Time ' $NOW)
        TS=$(date +"%s")
        v=$(printf "%s" 'DB ' $TS'.sql')
        printf '%s %s\n%s %s\n%s %s\n\n' $j $a $v>> _db/log.txt
        mysqldump -h 127.0.0.1 --column-statistics=0 -u$local_db_user --password=$local_db_pwd -P $local_db_port --force $db_name > _db/latest_local.sql
        mysqldump -h 127.0.0.1 --column-statistics=0 -u$local_db_user --password=$local_db_pwd -P $local_db_port --force $db_name > _db/${TS}.sql
    ;;
    deploy-local-db)
        task="mysql -h localhost -u$db_user --password=$db_pwd --force $db_name < $db_location/latest_local.sql"
        # ssh $remote_server_user@$remote_server_ip $task

        echo "Run this by hand: $task"
        echo $task | pbcopy
  ;;
    *)
        echo "It works! $project_folder"
    ;;
esac
