version: 2
jobs:
    build:
        docker:
          - image: circleci/php:7.2-node-browsers
        steps:
          - checkout
          - run:
              name: update-npm
              command: sudo npm install -g npm@latest
          - run: npm config set registry https://registry.npmjs.org/
          - run:
              name: Update composer to latest version
              command: sudo composer self-update
          - run:
              name: Update composer
              command: sudo composer update
          - run:
          - run:
              name: Update composer to latest version
              command: sudo composer install
          - run:
              name: Production
              command: npm run prod
          - run:
              name: Install rsync
              command: sudo apt install -y rsync
          - restore_cache:
              keys:
                  - composer-v1-{{ checksum "composer.json" }}
                  - composer-v1-
          - run: composer install -n --prefer-dist --ignore-platform-reqs
          - save_cache:
              key: composer-v1-{{ checksum "composer.json" }}
              paths:
                  - vendor

          - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}

          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                  - ./node_modules

          - run:
              name: Deploy
              command: ./util deploy
