version: 2
jobs:
    build:
        docker:
          - image: circleci/php:8.0-node-browsers
        steps:
          - checkout
          - run:
              name: update-npm
              command: sudo npm install -g npm@latest
          - run: npm config set registry https://registry.npmjs.org/
          - run:
              name: Update composer to latest version
              command: sudo composer self-update
          - run:
              name: Update composer
              command: sudo composer update
          - run:
              name: Update composer to latest version
              command: sudo composer install
          - run:
              name: install npm
              command: npm install
          - run:
              name: Production
              command: npm run prod
          - run:
              name: Install rsync
              command: sudo apt install -y rsync

          - run:
              name: Deploy
              command: ./util deploy
